---
title: 'Homework #8'
author: "Ben Porter"
date: "4/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1
# a.
```{r}
pbinom(19, 20, 0.92, lower.tail = FALSE)
```

Formula for p-value: 
P(X>=20) = P(X=20) = (n choose x)(p^x)((1-p)^(n-x))
=> (20 choose 20)(0.92^20)
=> 0.92^20 or around 0.1886933


# b.
```{r}
pval <- seq(0, 1, by = 0.0000001)

p <- 0
CIL <- 0
i <- 1
while(p < 0.05){
  p <- pbinom(19, 20, pval[i], lower.tail = FALSE)
  CIL <- pval[i]
  i <- i + 1
}
CI <- c(CIL, 1)
CI
```

# c.
```{r}
binom.test(20, 20, 0.05, alternative = "greater", conf.level = 0.95)
```

## Question 2
# a.
```{r}

CI1 <- replicate(1000, t.test(rnorm(50, 5, 1), y = rnorm(50, 5, 1))$conf.int)

CI2 <- replicate(1000, t.test(rnorm(50, 5, 1), y = rnorm(50, 5.5, 1))$conf.int)

S1Differ <- sum(ifelse(CI1[1,] < 0 & CI1[2,] > 0, 0, 1))
S2Differ <- sum(ifelse(CI2[1,] < 0 & CI2[2,] > 0, 0, 1))

S1Prop <- S1Differ/1000
S2Prop <- S2Differ/1000

print("Proportion for Scenario 1:")
S1Prop
print("Proportion for Scenario 2:")
S2Prop
```

## Question 3
```{r}
library(purrr)
n <- c(10,50,100,200)
p <- c(0.01,0.1,0.5)
for(i in n){
  for(j in p){
    X <- rbinom(100, size=i, prob=j)
    T <- sqrt(i)*(X/(i-j))
    print(ks.test(T, pnorm, 0, j*(1-j)))
  }
}
```

All of the p-values are smaller than 0.05, so each T distribution is not distributed like a N(0, p(1-p)) distribution.


## Question 5
# a.
```{r}
TimeBetween <- rexp(200, 1/2)
TimeIn <- rexp(200, 1/30)
ArrivalTime <- cumsum(TimeBetween)
DepartureTime <- ArrivalTime + TimeIn

t <- seq(1:120)
for(i in ArrivalTime){
  print((ArrivalTime[i] < t[i] & DepartureTime[i] > t[i]))
  i = i+1
}


In <- map_dbl(t, function(i){sum(ifelse(ArrivalTime < t[i] & DepartureTime > t[i],1, 0))})
plot(In, xlab = "Time in Minutes", ylab = "People in Restaurant")

```

# b.
```{r}
In1000 <- replicate(1000, map_dbl(t, function(i){sum(ifelse(cumsum(rexp(200, 1/2)) < t[i] & cumsum(rexp(200, 1/2)) + rexp(200, 1/30) > t[i],1, 0))}))
```

# i.
```{r}
TenAvg <- sum(In1000[10,])/1000
TenAvg
TwentyAvg <- sum(In1000[20,])/1000
TwentyAvg
ThirtyAvg <- sum(In1000[30,])/1000
ThirtyAvg
TwoHrAvg <- sum(In1000[120,])/1000
TwoHrAvg
```

# ii.
```{r}
OneHr <- In1000[60,]
t.test(OneHr, mu = 10, alternative = "greater")$p.value
```

# iii.
```{r}
OneHr <- In1000[60,]
t.test(OneHr, mu = 20, alternative = "less")$p.value
```


















